### ISSUE TITLE
Some notes can be cut even if there are many, many channels available

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#92]
This one affects "They're Going To Get You" from Doom. The high-pitched drone string "cuts out" even if there are ample channels available. In addition to that, the pizzicato strings "pop" as soon as the drone string is silenced. Very weird.

I have supplied a 25 second OGG of this happening. Sorry for this being loud, but I amp'd it up so you can hear. Happens between 20-21 seconds into the recording. increasing the number of chips to an obscene number "fixes" it, but it makes my recording software lag something fierce, so that's probably not a good remedy for it.
[getyou.zip](https://github.com/Wohlstand/libADLMIDI/files/2040743/getyou.zip)

**Comment by Wohlstand** [comment]
I think, I'll need to make the monitor of busyness of channels to look how many channels are busy in a real. And yeah, for a long notes (are don't stopping while key is held), I must make the protection from a kill and kill channels are already released...

**Comment by papiezak** [comment]
I also spotted note cutting bug, however much more extreme than that:
[note cut.zip](https://github.com/Wohlstand/libADLMIDI/files/2042570/note.cut.zip) - flute section is almost mute, compared to recording of what should it be. Midi file included. Every bank affected, no matter whether 2-op or 4-op, both OPL3 and OPN2.

**Comment by Wohlstand** [comment]
With this: https://github.com/Wohlstand/OPL3BankEditor/pull/71 and with this https://github.com/Wohlstand/libADLMIDI/commit/70c83caace9911dc5d8b80c1653c96b073f88e4a the issue is no more reproducing on your bank even with 4 chips! :fox_face: :+1: Tremolo-strings still persistent and no more dying!
I still to do some works until I'll apply it to everywhere...

**Comment by Wohlstand** [comment]
[getyou-fixed.zip](https://github.com/Wohlstand/libADLMIDI/files/2107648/getyou-fixed.zip)

**Comment by papiezak** [comment]
yeah, looks like fixed now.
midi that I linked few comments above still sounds broken, but it's most likely not connected to this issue; frankly speaking I have no bloody idea why it's that.

**Comment by Wohlstand** [comment]
As it's measurer problem in most, you need to download super-fresh version and run the full re-calculation to have that fixed. Embedded banks are NOT fixed yet as I wasn't ported fresh measurer into GenAdldata yet.

**Comment by papiezak** [comment]
It's not about embedded banks. I tested this damn thing on customs only. But I will try to recalculate it one more time

**Comment by Wohlstand** [comment]
About of the "n_toh03.mid", I have checked it's internals and I see the piccolo part (not a flute, but in it's same family) looks weird (it does usage of two tracks):, and seems note-on/note-offs are conflicting here... Even I have the code that does ordering of note on/offs to prevent note on goes before note off of previous note
![_2018-06-16_14-11-44](https://user-images.githubusercontent.com/6751442/41498183-836009fc-716f-11e8-81a2-5b9b73be3e65.png)

**Comment by Wohlstand** [comment]
Anyway, the reason of a crap in a piccolo is because of weird events in begin of the begin: (when I'll remove all of them except of "known", crap is going away):
![_2018-06-16_14-19-09](https://user-images.githubusercontent.com/6751442/41498213-5d49e7fa-7170-11e8-86da-f8b9ae35130a.png)
[crapicolo.ogg.zip](https://github.com/Wohlstand/libADLMIDI/files/2108062/crapicolo.ogg.zip)

**Comment by papiezak** [comment]
That are japanese GS midis for you - always so hacky :anger:

**Comment by Wohlstand** [comment]
Okay, the work against channel management and measurer has been completed!
Tremolo strings now surviving even on single-chip with your DMXOPL3 bank! :smile: :fox_face: 
![default](https://user-images.githubusercontent.com/6751442/41500698-6f10512a-719f-11e8-898a-c5f9d4e4c094.png)
The only left the work against junk NRPN events are causing piccolo play junk

**Comment by jpcima** [comment]
The thing of NRPN is that they are manufacturer specific.
So ADLMIDI probably tries to interpret messages intended for a different synth.

I would seem Joel has implemented these 3:
- 0x0108 MSB : vibrato speed
- 0x0109 MSB : vibrato depth
- 0x010A MSB : vibrato delay (ms)

It's possible that this specification was invented and does not match anything existing.
Does this specification of NRPN ring a bell to you?

**Comment by jpcima** [comment]
[xgspec.pdf](https://github.com/Wohlstand/libADLMIDI/files/2109219/xgspec.pdf)
It's XG. Found on document page 13.
Can the use of these events be done under condition of the previous message "XG system ON"?

**Comment by Wohlstand** [comment]
> Can the use of these events be done under condition of the previous message "XG system ON"?

It's need to turn them off when receiving `GX system ON` or `GM (1/2) system ON`

**Comment by jpcima** [comment]
ADLMIDI can be set to use GM mode by default.
Then, it will not conflict with such files which use the Roland specification.

It can have a state variable to designate the active mode which depends on sysex receiving: GM/XG/GS

**Comment by jpcima** [comment]
[MIDI Implementation Chart](https://docs.google.com/spreadsheets/d/1ZbPlh_L9coAzO9xQqmME1Jrt36L5vxM6gr4G4QVwiig/edit?usp=sharing)

I checked the manual of Roland SC-88 Pro and found these same NRPN with same ids.
This is the definition according to Roland.

![sc88vib](https://user-images.githubusercontent.com/17614485/41510969-3d1a63c0-726e-11e8-80c0-2ad7aff1841b.png)

**Comment by Wohlstand** [comment]
One thing on my VSC there are not working (working on YXG50). Anyway, it's now implemented support for SysEx events and some of them are handling for now, so, GS way (that requires SysEx) of percussions is works now. For temporary, I was set vibrato depth do not be controlled when GS mode is set. @papiezak  , Please test out the current result :wink:  Those damned NRPNs are must no more annoy this song.

**Comment by papiezak** [comment]
Tested it and yeah, it's alright! Thanks a ton!

_About NRPNs, I'm gonna wait until you do the same thing in libOPNMIDI because I'm curious whether sysex support will fix some bizarre bug that was present only on OPNMIDI and gave me tons of headache_

**Comment by Wohlstand** [comment]
About of libOPNMIDI, I in work to backport everything that was made here on libADLMIDI :wink:

**Comment by Wohlstand** [comment]
@papiezak , everything just now ported to libOPNMIDI too! :fox_face: :+1: 
For now you can enjoy same MIDI support as here now :fox_face:  :wink:

**Comment by Wohlstand** [comment]
I'll close this as the main trouble of this issue has completely resolved.
